buscoayuda4101/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'buscoayuda4101.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('polls.urls', namespace="principal")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^editar/(?P<id>\d+)$', views.editar_perfil, name='editar'),
    url(r'^login/$', views.login_view, name='login'),
    # url(r'^register', views.register, name='registro'),
    url(r'^register', views.registerTrabajador, name='registro'),
    url(r'^register', views.registerTrabajador, name='registro'),
    url(r'^logout$', views.logout),
    url(r'^trabajador/(?P<pk>\d+)$', views.detail),
    url(r'^detail/(?P<id>\d+)/$', views.detalle_trabajador, name='detalle'),
    url(r'^addComment', views.add_comment),
    url(r'^mostrarComentarios/(?P<idTrabajador>\d+)$', views.mostrarComentarios),
    url(r'^mostrarTrabajadores/(?P<tipo>\w+)$', views.mostrarTrabajadores),
    url(r'^mostrarTrabajadores', views.mostrarTrabajadores),
    url(r'^tipoServicio/(?P<pk>\d+)$', views.getTiposDeServicio),
]

polls/models.py
# coding=utf-8
from __future__ import unicode_literals

from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm


class TiposDeServicio(models.Model):
    nombre = models.CharField(max_length=1000)
    imagen = models.ImageField(upload_to='services')

    def __unicode__(self):
        return u'{0}'.format(self.nombre)


class Trabajador(models.Model):
    nombre = models.CharField(max_length=1000)
    apellidos = models.CharField(max_length=1000)
    aniosExperiencia = models.IntegerField()
    tiposDeServicio = models.ForeignKey(TiposDeServicio, null=True)
    telefono = models.CharField(max_length=1000)
    correo = models.CharField(max_length=1000)
    imagen = models.ImageField(upload_to='photos')
    usuarioId = models.OneToOneField(User, null=True)


class Comentario(models.Model):
    texto = models.CharField(max_length=1000)
    trabajador = models.ForeignKey(Trabajador, null=True)
    correo = models.CharField(max_length=1000)

class registroTrabajadorForm(ModelForm):
    class Meta:
        model = Trabajador
        fields = ['nombre', 'apellidos', 'aniosExperiencia', 'tiposDeServicio', 'telefono', 'correo', 'imagen']


class TrabajadorForm(ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus nombres'})
    )
    apellidos = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus apellidos'})
    )
    aniosExperiencia = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad de años de experiencia'}),
        label='Años De Experiencia'
    )
    tiposDeServicio = forms.ModelChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=TiposDeServicio.objects.all(),
        empty_label='Seleccione el tipo de servicio que ofrecerá',
        label='Tipo De Servicio'
    )
    telefono = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Número telefónico'}),
        label='Teléfono'
    )
    correo = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        label='Correo'
    )

    class Meta:
        model = Trabajador
        fields = ['nombre', 'apellidos', 'aniosExperiencia', 'tiposDeServicio', 'telefono', 'correo', 'imagen']

class TrabajadorEditForm(ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus nombres'})
    )
    apellidos = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese sus apellidos'})
    )
    aniosExperiencia = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad de años de experiencia'}),
        label='Años De Experiencia'
    )
    tiposDeServicio = forms.ModelChoiceField(
        widget=forms.Select(attrs={'class': 'form-control'}),
        queryset=TiposDeServicio.objects.all(),
        empty_label='Seleccione el tipo de servicio que ofrecerá',
        label='Tipo De Servicio'
    )
    telefono = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Número telefónico'}),
        label='Teléfono'
    )
    correo = forms.CharField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
        label='Correo'
    )

    class Meta:
        model = Trabajador
        fields = ['nombre', 'apellidos', 'aniosExperiencia', 'tiposDeServicio', 'telefono', 'correo', 'imagen']


class UserForm(ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        label='Usuario'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label='Contraseña'
    )

    class Meta:
        model = User
        fields = ['username', 'password']

polls/views.py
# coding=utf-8
import datetime

import boto
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt

from .models import Trabajador, TrabajadorForm, UserForm, Comentario, registroTrabajadorForm, TrabajadorEditForm
from .models import TiposDeServicio
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib import auth


def index(request):
    trabajadores = Trabajador.objects.all()
    tipos_de_servicios = TiposDeServicio.objects.all()
    form_trabajador = TrabajadorForm(request.POST)
    form_usuario = UserForm(request.POST)

    context = {'trabajadores': trabajadores, 'tipos_de_servicios': tipos_de_servicios,
               'form_trabajador': form_trabajador, 'form_usuario': form_usuario, 'base_url': settings.STATIC_URL}
    return render(request, 'polls/index.html', context)


def logout(request):
    auth.logout(request)
    messages.info(request, "Cerraste sesión exitosamente", extra_tags="alert-info")
    return HttpResponseRedirect('/')


def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = User.objects.create_user(username=username, password=password)
        user.first_name = request.POST.get('nombre')
        user.last_name = request.POST.get('apellidos')
        user.email = request.POST.get('correo')
        user.save()

        nuevo_trabajador=Trabajador(nombre=request.POST['nombre'],
                                      apellidos=request.POST['apellidos'],
                                      aniosExperiencia=request.POST.get('aniosExperiencia'),
                                      tiposDeServicio=TiposDeServicio.objects.get(pk=request.POST.get('tiposDeServicio')),
                                      telefono=request.POST.get('telefono'),
                                      correo=request.POST.get('correo'),
                                      imagen=request.FILES['imagen'],
                                      usuarioId=user)
        nuevo_trabajador.save()

    return HttpResponseRedirect('/')


def editar_perfil(request, id):
    print '------------ dentro de editar usuario ------------'
    trabajador=Trabajador.objects.get(usuarioId=id)
    if request.method == 'POST':
        # formulario enviado
        form_trabajador = TrabajadorEditForm(request.POST, request.FILES, instance=trabajador)

        if form_trabajador.is_valid():
            print '------------ formulario valido ------------'
            # formulario validado correctamente
            form_trabajador.save()
            print '------------ redireccionando ------------'
            return HttpResponseRedirect('/')

    else:
        print '------------ formulario para actualizar ------------'
        # formulario inicial
        form_trabajador = TrabajadorEditForm(instance=trabajador)

    context = {'form_trabajador': form_trabajador}
    return render(request, 'polls/editar.html', context)

@csrf_exempt
def add_comment(request):
    if request.method == 'POST':
       new_comment = Comentario(texto=request.POST.get('texto'),
                                      trabajador=Trabajador.objects.get(pk=request.POST.get('trabajador')),
                                      correo=request.POST.get('correo'))
       new_comment.save()
    return HttpResponse(serializers.serialize("json", [new_comment]))

@csrf_exempt
def mostrarTrabajadores(request, tipo=""):
    if tipo == "":
      lista_trabajadores = Trabajador.objects.all()
    else:
      lista_trabajadores = Trabajador.objects.select_related().filter(tiposDeServicio__nombre__icontains=tipo)


    return HttpResponse(serializers.serialize("json", lista_trabajadores))

@csrf_exempt
def mostrarComentarios(request, idTrabajador):
    lista_comentarios =Comentario.objects.filter(trabajador=Trabajador.objects.get(pk=idTrabajador))

    return HttpResponse(serializers.serialize("json", lista_comentarios))

def getTiposDeServicio(request, pk):
    tipo = TiposDeServicio.objects.get(pk=pk)
    return HttpResponse(serializers.serialize("json", [tipo]))


def detalle_trabajador(request, id):
    trabajador = get_object_or_404(Trabajador, pk=id)
    params = {'trabajador': trabajador}
    return render(request, "polls/detalle.html", params)


def detail(request, pk):
    trabajador = get_object_or_404(Trabajador, pk=pk)
    return HttpResponse(serializers.serialize("json", [trabajador]))


def registerTrabajador(request):
    if request.method == 'POST':
        form = registroTrabajadorForm(request.POST, request.FILES)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.create_user(username=username, password=password)
        user.first_name = request.POST.get('nombre')
        user.last_name = request.POST.get('apellidos')
        user.email = request.POST.get('correo')
        user.save()
        nuevo_trabajador = Trabajador(nombre=request.POST['nombre'],
                                      apellidos=request.POST['apellidos'],
                                      aniosExperiencia=request.POST.get('aniosExperiencia'),
                                      tiposDeServicio=TiposDeServicio.objects.get(
                                          pk=request.POST.get('tiposDeServicio')),
                                      telefono=request.POST.get('telefono'),
                                      correo=request.POST.get('correo'),
                                      imagen=request.FILES['imagen'],
                                      usuarioId=user)
        nuevo_trabajador.save()
        return HttpResponseRedirect(reverse('principal:index'))
    else:
        form_trabajador = registroTrabajadorForm()
        form_usuario = UserForm()
    return render(request, 'polls/registro.html ', {'form_trabajador': form_trabajador, 'form_usuario': form_usuario})


def login_view(request):

    if request.user.is_authenticated():
        # return redirect(reverse('media1:index'))
        return render(request, "polls/index.html")

    mensaje = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # return redirect(reverse('media1:index'))
            return render(request, "polls/index.html")
        else:
            mensaje = 'Credenciales de acceso incorrectas'

    return render(request, 'polls/login.html', {'mensaje': mensaje})

polls/templates/polls/detalle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalle Independiente</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <script src="/designMatch/recursos/jquery.bootpag.min.js"></script>
</head>
<body>
<h2>{{ trabajador.nombre }} {{ trabajador.apellidos }} - {{ trabajador.tiposDeServicio.nombre }}</h2>
</body>
</html>

polls/templates/polls/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Editar trabajador</title>
</head>
<body>
    <form action="{% url 'principal:editar' id=1 %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form_trabajador.as_p }}
        {{ form_usuario.as_p }}
        <input id="id_grabar" type="submit" value="Editar"/>
    </form>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BuscoAyuda</title>
</head>
<body>
    <ul class="nav navbar-nav navbar-right" style="padding-right: 20px">
        <li><a href="{% url 'principal:registro' %}" id="id_register"><span class="glyphicon glyphicon-user"></span> Registrarse</a></li>
        <li> <a href="{% url 'principal:login' %}" id="id_login"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
        <li> <a href="{% url 'principal:editar' id=1 %}" id="id_editar"><span class="glyphicon glyphicon-log-in"></span>Editar</a></li>

    </ul>
    <div class="jumbotron" style="padding-left: 20px; height: 50%">
        <h1>Busco Ayuda</h1>
        <p>Encuentra aquí la ayuda que necesitas.</p>
        {% if user.is_authenticated %}
        <span>Bienvenido(a) {{ user.first_name }}</span>
        {% endif %}
        <div id="trabajadores">
            {% for trabajador in trabajadores %}
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading" style="text-align: center; background-color: black;">
                        <span style="color: white; font-size: large;">{{ trabajador.tiposDeServicio.nombre }}</span>
                    </div>
                    <div class="panel-body" style="text-align: center">
                        <a class="trabajador" href="{% url 'principal:detalle' id=trabajador.id %}" data-form="{{ trabajador.id }}" style="text-decoration: none;">
                            <!--suppress HtmlUnknownTarget -->
                            <img class="thumbnail img-responsive center-block"
                            src="/media/{{ trabajador.imagen }}" width="100" height="100">
                            <span>{{ trabajador.nombre }} {{ trabajador.apellidos }} - {{ trabajador.tiposDeServicio.nombre }}</span>
                        </a>
                        <span>Telefono: {{ trabajador.telefono }}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

polls/templates/polls/login.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <div class ='row'>
        <div class="col-md-4 col-md-offset-4">
            <div class="page header">
                <h2>Login</h2>
            </div>
            {% if mensaje %}
            <div class="alert alert-danger">
                {{ mensaje }}
            </div>
            {% endif %}

            <form method="post" action="">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" form="username">Nombre de usuario</label>
                    <input type="text" id="username" name="username" class="form-control" value="{{ username }}">
                </div>

                <div class="form-group">
                    <label for="password">contraseña</label>
                    <input type="password" name="password" id="password" class="form-control">
                </div>
                <button type="submit" id="aceptar" class="btn btn-primary">loggin</button>
                <a href="{% url 'principal:index' %}" class="btn btn-primary">Cancelar</a>
            </form>
        </div>
    </div>
</body>
</html>

polls/templates/polls/registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registrar trabajador</title>
</head>
<body>
    <form action="{% url 'principal:registro' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form_trabajador.as_p }}
        {{ form_usuario.as_p }}
        <input id="id_grabar" type="submit" value="Agregar"/>
    </form>
</body>
</html>